name: Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/configure-pages@v3
        id: pages
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build Website
        env:
            FREEZER_BASE_URL: ${{ steps.pages.outputs.base_url }}
        run: python main.py sitedata/ --build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2